### ISSUE TITLE
Blok dashboard: are we filtering out users with other tracking protection add-ons?

### ISSUE THREAD

**Issue by groovecoder** [mozilla/testpilot_metrics#11]
We should filter out users with other tracking protection add-ons so we know the breakage that is reported is caused by our add-on and not the others.

**Comment by ghost** [comment]
I agree that that approach would reduce potential confounds.  However, addons are a separate part of the Telemetry packet and increases the complexity of the pipeline by orders of magnitude.  @ilanasegall is in a better position to communicate whether this can be put on our backlog, but it's not a minor task.
