### ISSUE TITLE
USearch Dashboard Query Review

### ISSUE THREAD

**Issue by ghost** [mozilla/testpilot_metrics#8]
I'd appreciate a review of the USearch queries.  I'm splitting this up and giving the better ones for onboarding to @sunahsuh and the more complex ones to @emtwo.

@sunahsuh please review:
- [README.md](https://github.com/mozilla/testpilot_metrics/blob/master/universal_search_metrics/README.md)
- [avgBasicRecommendationsByDate.sql](https://github.com/mozilla/testpilot_metrics/blob/master/universal_search_metrics/avgBasicRecommendationsByDate.sql)
- [distBasicRecommendationsByDate.sql](https://github.com/mozilla/testpilot_metrics/blob/master/universal_search_metrics/distBasicRecommendationsByDate.sql)
- [populationPingsByDate.sql](https://github.com/mozilla/testpilot_metrics/blob/master/universal_search_metrics/populationPingsByDate.sql)

@emtwo please review:
- [engagementByCohort.sql](https://github.com/mozilla/testpilot_metrics/blob/master/universal_search_metrics/engagementByCohort.sql)
- [shownTakenByDate.sql](https://github.com/mozilla/testpilot_metrics/blob/master/universal_search_metrics/shownTakenByDate.sql)
- [shownTakenByTypeDate.sql](https://github.com/mozilla/testpilot_metrics/blob/master/universal_search_metrics/shownTakenByTypeDate.sql)

I know this is a lot (it's a whole dash), so I understand if it takes a little time.  @sunahsuh LMK if you have questions about Re:dash or Presto.

**Comment by emtwo** [comment]
@rayborn I've looked over a couple of the queries, and 1 more to go. Here are my comments so far:

**For shownTakenByTypeDate.sql and shownTakenByDate.sql:**
1. That's a tough read with the manipulation of `ts` in the `SELECT` clause. Is there any way you could simplify it? I'm still not sure I fully understand it, but you said you're doing that to avoid having the most recent week with incomplete data. I personally wouldn't mind seeing data that is 1 week behind in exchange for a more robust/readable query. Alternatively, a really thorough comment on what is going on there would be great!
2. It's not clear to me why `ts` is restricted by certain dates. Could we have a comment on that as well? I'm also unsure why those restrictions don't seem to appear in the graph. Are we only interested in data <= July 6th and >= Aug 9th?

**Comment by sunahsuh** [comment]
On avgBasicRecommendationsByDate:

Re: the week boundary calculation (L12-15), a potential alternative would be:

``` sql
DATE_TRUNC('day', FROM_UNIXTIME(ts/POWER(10, 9))) -
  (DAY_OF_WEEK(FROM_UNIXTIME(ts/POWER(10, 9)) - DAY_OF_WEEK(NOW()) + 7) % 7 as week
```

Which may be a wash, but it does use semantically meaningful functions vs just math on epoch-seconds (or nanoseconds D=)

Simliarly, for the clause  on L28 `AND ts < 1000*1000*1000*FLOOR(TO_UNIXTIME(CURRENT_TIMESTAMP)/(24*60*60))*(24*60*60)`, I do think `AND ts < 1000*1000*1000* TO_UNIXTIME(DATE_TRUNC('day', CURRENT_TIMESTAMP))` would be a cleaner/more semantically meaningful way to write that.

The select clause on L53: `(1.0*label_interactions/num_users) AS avg_interactions` there is a Presto `CAST()` function (https://prestodb.io/docs/current/functions/conversion.html)

Overall, a comment explaining the query at a high level would be fantastic, as well as comments throughout -- I suspect these executive summary dashboards are particularly going to be used as examples that folks use as a starting point, might be possibly a bit longer-lived, and the primary responsibility might change hands in the future/might require reworking down the line after you've forgotten what it did ;) All reasons why it might be worth a little extra effort to document

**Comment by sunahsuh** [comment]
One more thing on avgBasicRecommendationsByDate: is uuid (and grouping by uuid) necessary in the tmp_weekly_usertotals CTE?

Edit: Never mind, I see that it's used in the weekly user count

**Comment by sunahsuh** [comment]
distBasicRecommendationsByDate:
Same re: date math/comments as above

Only other thing I'm curious about: What does `WHERE cnt > 100` on L43?

populationPingsByDate:
Same re: date math/comments as above

Otherwise, looks good to me!

And thanks for tagging me in the review, it was a good excuse to look deeper into re:dash and especially to see it in the context of use =)
